export const environment = {
  production: true,
  baseUrl:"https://test.adf.house/connector/api",
  token: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjQ1MjRkY2I5ZWQwNzUwMjUxZTRjNGY1MmE1MjdiZGQ1MTcyZGQ2YzJiMzQ5YzEwYjBkODEwZGJhZWJiN2EzZDE0NmU1MWI2YjIyNzRjZDA5In0.eyJhdWQiOiI0IiwianRpIjoiNDUyNGRjYjllZDA3NTAyNTFlNGM0ZjUyYTUyN2JkZDUxNzJkZDZjMmIzNDljMTBiMGQ4MTBkYmFlYmI3YTNkMTQ2ZTUxYjZiMjI3NGNkMDkiLCJpYXQiOjE2MzI3OTAzMDEsIm5iZiI6MTYzMjc5MDMwMSwiZXhwIjoxNjY0MzI2MzAxLCJzdWIiOiI1Iiwic2NvcGVzIjpbXX0.fNfHSlRoomGHv45bX2V2Cb_Q3jfR5d0MgSgqJbD8EEiucgEv2PSKS-ki2Pl_z8mU7m3ZcCnDaq1IMb8D9bPngxvv_NGsIjRU5bwo1LfBVLsaHTlPPr7ocrRi7VPIRjT4ZmhdxrUQCVHbSYfBqyiNVDnVwzmdT1yRqMsuK4YRSXYLVpMbP31fu4JbstqJhV4h-xr9h0kNlcLhaLF1lR8OJcnrvrS8PK5c_7RCjkgN92gpipxC1NxvseIc6xPFImBaAz8C16wsPFHnoVT-rWZV5MWcaOVCtjnuzMMS20a6oJcrVB9pCBYaqLBotNQkWo6kjIYcnnzAEQbJuXJJMR7gnT39CXJV8B_8mLhBmyTqpMJnx9PHALShQ6Skn668r0rfTBmQ8O6P8yTo9LDZa5Irm9H06kpcZy3_Ua5FTNjD7Nbi_el0_pV3ME_hLRvIy7UTXHQsB0k0LWilSuEQ4hIc0umzBE6l_YudoJDTJ4Db96w8Vds0SMgc-hSgQDDLoYuLziiBizOYM9nTEgwq6nawSrLPWAaK0_JLWRGzrWVsQUarzuN4-tf10GgA55i0joSvcBZVP9b1C9poa0gEy_3UL8QzhKEXVUdKllfqICvdCBiEEUeU4n8hBIfMIdwEYcv-62VSGQP7FqgtckzabiWl6jdrt1yi7EhCaOdoBDf_NkA",
  logSrc: 'assets/logo.png',
  currency: 'EGP',
  copyright1: 'Tp',
  copyrightUrl: 'https://tps-egy.com/',
  copyright2: 'TPS',
  categoryId: 56,
  location_id: 9,
  voidInvoiceId: "1",
  FBOrders: 12,
  locationParty: 26,
  groupA: 5,
  groupB: 6,
  groupC: 1,
  groupD1: 3, // hospitalityGroupD
  groupD2: 2, // generalHospitalityGroupD
  groupD3: 7,// partiesHospitalityGroupD
  groupD4: 4, // hotelHospitalityGroupD
  groupE: 8,
  groupF: 12, // business location id
  groupH_I: 15, // employee Sales Customer Group id
  beverageCategoryAndSubCategoryId: 83,
  foodCategoryAndSubCategoryId: 82,
  brokenCategoryAndSubCategoryId: 84,
  shishaCategoryAndSubCategoryId: 87,
  otherCategoryAndSubCategoryId: 88,
  MarketCategoryAndSubCategoryId: 93,
  ActivitiesCategoryAndSubCategoryId: 90,
  SecurityCategoryAndSubCategoryId: 133,
  LaundryCategoryAndSubCategoryId: 92,
  HairdresserCategoryAndSubCategoryId: 91,
  AnimalsCategoryAndSubCategoryId: 96,
  service15: 1,
  service25: 2,
  comboProductCategory: 185,
  partiesRentalCategoryAndSubcategoryID: 152,
  depreciation: 188,
  SupplementaryFund: 189,
  weddingCalculationsRatios: 112,
  weddingCalculationsCategoriesSubCategories: 111,
  videoPhotosCalculationsRatios: 107,
  videoPhotosCalculationsCategoriesSubCategories: 103,
  laserCalculationsRatios: 116,
  laserCalculationsCategoriesSubCategories: 115,
  DJCalculationsRatios: 119,
  DJCalculationsCategoriesSubCategories: 118,
  SmokingCalculationsRatios: 122,
  SmokingCalculationsCategoriesSubCategories: 121,
  PartiesFixedItemsScreensCalculationCategoriesSubCategories: 125,
  PartiesScreensCalculationRatio: 126,
  PartiesFixedItemsSoundsCalculationCategoriesSubCategories: 128,
  PartiesSoundsCalculationRatio: 129,
  PartiesFixedItemsLightsCalculationCategoriesSubCategories: 131,
  PartiesLightsCalculationRatio: 132,
  PartiesSecurityCalculationCategoriesSubCategories: 133,
  PartiesParkingCalculationRatio: 134,
  PartiesTipsCalculationCategoriesSubCategories: 136,
  PartiesTipsCalculationRatio: 137,
  PartiesHallopeningfeesCalculationCategoriesSubCategories: 139,
  PartiesHallopeningfeesCalculationRatio: 140,
  PartiesMaintenanceCalculationCategoriesSubCategories: 142,
  PartiesMaintenanceCalculationRatio: 143,
  PartiesExternalPurchasesCalculationCategoriesSubCategories: 145,
  PartiesExternalPurchasesCalculationRatio: 146,
  partiesRatio_2: 147,
  partiesRatio_3: 148,
  fixedItemValues: 149,
  FixedItemsRatios: 150,
  weddingDesignerCalculationsRatios: 184,
  weddingDesignerCalculationsCategoriesSubCategories: 183,
  roomServiceLocation: "8",
  GeneralWareHouseLocationID: '38',
  FoodBeverageMainWareHouseLocationID: '28',
  GeneralWareHouseCategory1: '216',
  GeneralWareHouseCategory2: '217',
};
export const lang = {
  userLang: localStorage.getItem('lang') || 'ar'
};
