export const LangAr = {
  table: 'ترابيزه',
  room: 'غرفه',
  Chalet: 'شاليه',
  Checkpinding: 'طلب معلق',
  Checkorder: 'طلب',
  Checkpacked: 'معباه',
  Checkdelivered: 'تم التوصيل',
  ordered: 'طلب',
  packed: 'تعبئه',
  delivered: 'توصيل',
  foodInsight: 'رؤية الطعام',
  paid: 'مدفوع',
  due: 'مستحق',
  cancelsure: "هل أنت متأكد؟",
  cancelParagraph: ".هل تريد حقًا إلغاء هذا الطلب ؟",
  cancelClose: "غلق",
  cancelBtn: "تأكيد إلغاء",
  cost: "المبلغ",
  part: "القسم",
  totalPayment: "المبلغ الإجمالي",
  orderDetails: "تفاصيل الطلبات",
  report: "تقرير المراجع المالي",
  groupA: "اللإيراد العام",
  groupB: "الاوفسر",
  groupC: "حساب الشركات",
  groupD: "الضيافات",
  groupE: "افطارات الفندق",
  groupF: "تعاقدات قسم أغذيه ومشروبات",
  groupG: "قسم الحفلات",
  groupH: "حسابات داخلية قسم مراقبة أ.غ.م",
  groupI: "حسابات داخلية المخازن العمومية",
  food: "مأكولات",
  beverage: "مشروبات",
  discount: "خصم",
  other: "آخر",
  shisha: "شيشة",
  broken: "توالف",
  service: "الخدمات",
  total: "إجمالي",
  cash: "نقد",
  visa: "فيزا",
  outCome: "منصرف من التكلفة",
  dueCome: "مبيعات العاملين مستحقة الدفع",
  paidCome: "مبيعات العاملين مدفوعة",
  hotelRoom: "غرف الفندق",
  Officer: "اوفسر",
  Companies: "شركات",
  Hospitality: "ضيافة",
  generalHospitality: "الضيافة العامة",
  partiesHospitality: " ضايفه حفلات",
  hotelHospitality: "ضيافه إسكان",
  hotelBreakfast: "إفطار الفندق",
  Customers: "عملاء",
  incomeTotal: "إجمالي إيراد المطاعم",
  Finance: "المالية",
  Security: "أمن",
  hairdresser: "مصفف شعر رجالي",
  Activities: "أنشطة",
  laundry: "مغسلة",
  market: "ماركت",
  animals: "القسم الإداري",
  reportFb: "تقرير",
  weddingRevenue: "إيراد الافراح",
  weddingData: "بيانات الفرح",
  AGM: "ا.غ.م",
  otherIncome: "إيرادات اخري",
  digitalVision: "ديجيتال فيجين",
  sounds: "الصوتيات",
  Diamondros: "دايموند روز",
  wedding: "الزفه",
  date: "التاريخ",
  weapon: "السلاح",
  people: "الافراد",
  hall: "القاعه",
  Paymentreceipt: "ارقام ايصالات السداد",
  depreciation: "هالك",
  lights: "اضاءه",
  SupplementaryFund: "صندوق تكميلي",
  security: "امن",
  maintenance: "صيانه قاعات",
  partiesRatio_2: "نسبه 2 %",
  partiesRatio_3: "نسبه 3 %",
  Rental: "الايجار",
  sound: "ساوند",
  screen: "شاشات",
  Covers: "كوفير",
  tips: "إكراميات",
  laser: "الليزر",
  allotments: "مخصصات",
  Allowancetoopenhalls: "بدل فتح قاعه",
  TotalSuppliers: "نسبه المتعهد",
  LaserAndDJAndSmoking: "ليزر و دي جي و دخان",
  VideoAndPhoto: "فيديو وصور",
  KoshaAndCenterpiece: "ميليهات الورد والكوشة",
  TotalContractValue: "إجمالي قيمه العقد",
  TotalADFH: "إجمالي إيراد الدار",
  TotalADFHRatio: "إجمالي نسبه الدار",
  Parties: "قسم الحفلات",
  TotalADFHWthout: "إجمالي إيراد الدار بدون 15%",
  invoice: "رقم الفاتوره",
  SuppliersRatio: "نسب المتعهدين",
  ProductName: "اسم المنتج",
  SoldQuantity: "الكمية المباعة",
  ProductCost: "تكلفة المنتج",
  TotalProductCost: "اجمالى تكلفة المنتج",
  SellingCost: "متوسط تكلفة البيع ",
  TotalSellingCost: "اجمالي تكلفة البيع",
  TotalProfit: "ربح الوحدة",
  Ratio: "النسبه",
  Stock: "المخزون",
  ProductSelling: "بيع المنتج",
  Variation: "الاختلافات",
  category: "فئه",
  StockValueByCostPrice: "قيمه المخزون الحاليه (بسعر الشراء)",
  StockValuebySellingPrice: "قيمه المخزون الحاليه (بسعر البيع)",
  mw1: "توزيع مصروفات المخازن العمومية على الأقسام",
  mw2: "بيان توزيع تكاليف الصيانة على الأقسام",
  mw3: "تحليل المعاملات",
  mw4: "إجمالي تحليل المعاملات",
  mw5: "جرد المخازن العمومية"
};
