export const LangEn = {
  table: 'table',
  room: 'room',
  Chalet: 'Chalet',
  Checkpinding: "pending order",
  Checkorder: "ordered",
  Checkpacked: "packed",
  Checkdelivered: "delivered",
  ordered: "ordered",
  packed: "packed",
  delivered: "delivered",
  foodInsight: "Food Insight",
  paid: "paid",
  due: "due",
  cancelsure: "Are you sure?",
  cancelParagraph: "Do you really want to cancel this order?.",
  cancelClose: "Close",
  cancelBtn: "Confirm Cancel",
  totalPayment: "Total Payment",
  orderDetails: "Order Details",
  report: "Finance Reviewer Report",
  groupA: "General Income",
  groupB: "Officers",
  groupC: "Companies",
  groupD: "Hospitalities",
  groupE: "Hotel Breakfast",
  groupF: "F&B Orders",
  groupG: "Banquet Department",
  groupH: "Internal Accounts For Food & Beverage Cost Department",
  groupI: " Internal Accounts For General Warehouse",
  food: "food",
  beverage: "beverages",
  discount: "discount",
  other: "other",
  shisha: "shisha",
  broken: "broken",
  service: "service",
  total: "total",
  cash: "cash",
  visa: "visa",
  outCome: "Outcome From Department Cost",
  dueCome: "Due Employee Outcome",
  paidCome: "Paid Employee Outcome",
  hotelRoom: "Hotel Rooms",
  Officer: "Officers",
  Companies: "Companies",
  Hospitality: "Hospitality",
  generalHospitality: "General Hospitality",
  partiesHospitality: "Banquet  Department Hospitality",
  hotelHospitality: "Hotel Department Hospitality",
  hotelBreakfast: "Hotel Breakfast",
  Customers: "Customers",
  incomeTotal: "Restaurants Income Total",
  Finance: "Finance",
  Security: "Security",
  hairdresser: "Men's hairdresser",
  Activities: "Activities",
  laundry: "laundry",
  market: "market",
  animals: "Administration Department",
  reportFb: "report",
  weddingRevenue: "Wedding Revenue",
  weddingData: "wedding Data",
  AGM: "A.G.M",
  otherIncome: "other Income",
  digitalVision: "digital Vision",
  sounds: "sounds",
  Diamondros: "Diamond Ros",
  wedding: "wedding",
  date: "date",
  weapon: "weapon/partyName",
  people: "people",
  hall: "the hall",
  Paymentreceipt: "Payment Receipt",
  depreciation: "depreciation",
  lights: "lights",
  SupplementaryFund: "SupplementaryFund",
  security: "secuirty",
  maintenance: "maintenance",
  partiesRatio_2: "Ratio 2%",
  partiesRatio_3: "Ratio 3%",
  Rental: "Rental",
  sound: "sound",
  screen: "screen",
  Covers: "Covers",
  tips: "Tips",
  laser: "Laser",
  allotments: "Financial Allocations",
  TotalSuppliers: " Total Suppliers Ratio",
  LaserAndDJAndSmoking: "Laser, DJ And Smoking",
  VideoAndPhoto: "Video And Photo",
  KoshaAndCenterpiece: "Kosha And Centerpiece",
  Allowancetoopenhalls: "Allowance To Open Halls",
  TotalContractValue: "Total Contract Value",
  TotalADFH: "Total ADFH",
  TotalADFHRatio: "Total ADFH Ratio",
  Parties: "Banquet  Department",
  TotalADFHWthout: "Total ADFH Without 15%",
  invoice: "invoice #",
  SuppliersRatio: " Suppliers Ratio",
  ProductName: "Product Name",
  SoldQuantity: "Sold Quantity",
  ProductCost: "Product Cost",
  TotalProductCost: "Total Product Cost",
  SellingCost: "average Selling Cost",
  TotalSellingCost: "Total Selling Cost",
  TotalProfit: "Unit Profit",
  Ratio: "Ratio",
  Stock: "Stock",
  ProductSelling: "Product Selling",
  Variation: "Variation",
  category: "Category",
  StockValueByCostPrice: "StockValue By (cost price)",
  StockValuebySellingPrice: "StockValue By (selling price)",
  cost: "cost",
  part: "Department",
  mw1: "Distribution of general warehouse outcomes to departments",
  mw2: "Statement of  maintenance cost distribution on departments",
  mw3: "Transactions analysis",
  mw4: "Total transactions analysis",
  mw5: "General warehouse inventory"
};
